INSERT INTO MEMBERS(FIRST_NAME, LAST_NAME, MAIL_ADDRESS) VALUES('John', 'Doe', 'john.doe@temp.nl');
INSERT INTO MEMBERS(FIRST_NAME, LAST_NAME, MAIL_ADDRESS) VALUES('Maria', 'Doe', 'maria.doe@temp.com');
INSERT INTO MEMBERS(FIRST_NAME, LAST_NAME, MAIL_ADDRESS) VALUES('Berry', 'Haze', 'berry.haze@temp.com');
INSERT INTO MEMBERS(FIRST_NAME, LAST_NAME, MAIL_ADDRESS) VALUES('Edward', 'Link', 'adward.link@temp.nl');